//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeDeck.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeDeck.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string ant {
            get {
                return ResourceManager.GetString("ant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta carta ya está en tus favoritos..
        /// </summary>
        public static string avisocon {
            get {
                return ResourceManager.GetString("avisocon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al añadir favorito..
        /// </summary>
        public static string avisoerr {
            get {
                return ResourceManager.GetString("avisoerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes iniciar sesión para añadir favoritos..
        /// </summary>
        public static string avisosesfav {
            get {
                return ResourceManager.GetString("avisosesfav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorito añadido correctamente..
        /// </summary>
        public static string avisosucc {
            get {
                return ResourceManager.GetString("avisosucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        public static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información personal.
        /// </summary>
        public static string datospers {
            get {
                return ResourceManager.GetString("datospers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debilidad.
        /// </summary>
        public static string deb {
            get {
                return ResourceManager.GetString("deb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los derechos reservados..
        /// </summary>
        public static string derechos {
            get {
                return ResourceManager.GetString("derechos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string img {
            get {
                return ResourceManager.GetString("img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando cartas....
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay cartas..
        /// </summary>
        public static string nocard {
            get {
                return ResourceManager.GetString("nocard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay cartas que coincidan..
        /// </summary>
        public static string nocoin {
            get {
                return ResourceManager.GetString("nocoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página.
        /// </summary>
        public static string pag {
            get {
                return ResourceManager.GetString("pag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rareza.
        /// </summary>
        public static string rar {
            get {
                return ResourceManager.GetString("rar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Síguenos en:.
        /// </summary>
        public static string redes {
            get {
                return ResourceManager.GetString("redes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string sig {
            get {
                return ResourceManager.GetString("sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
    }
}
